-- -- Set custom respawning
--
-- local PLAYER = FindMetaTable("Player")
-- TODO: change this
-- PLAYER.BaseResetSpawnPosition = PLAYER.ResetSpawnPosition
-- function PLAYER:ResetSpawnPosition(bReset, bLeave)
-- 	if self:BaseResetSpawnPosition(bReset, bLeave) then
-- 		self:SetName("one")
-- 		self:SetKeyValue("classname", "")
-- 	end
-- end
